tinymce.addI18n('fr_FR',{
"Cut": "Taglia",
"Heading 5": "En-t\u00eate 5",
"Header 2": "Titolo 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Il tuo browser non supporta l'accesso diretto agli appunti.. Per favore usa le shortcuts Ctrl+X\/C\/V.",
"Heading 4": "En-t\u00eate 4",
"Div": "Div",
"Heading 2": "En-t\u00eate 2",
"Paste": "Incolla",
"Close": "Chiudi",
"Font Family": "Polices de caract\u00e8res",
"Pre": "Pre",
"Align right": "Aligner \u00e0 droite",
"New document": "Nuovo Documento",
"Blockquote": "Citazione",
"Numbered list": "Num\u00e9rotation",
"Heading 1": "En-t\u00eate 1",
"Headings": "En-t\u00eates",
"Increase indent": "Augmenter le retrait",
"Formats": "Formati",
"Headers": "Titoli",
"Select all": "Tout s\u00e9lectionner",
"Header 3": "Titolo 3",
"Blocks": "Blocs",
"Undo": "Annuler",
"Strikethrough": "Barr\u00e9",
"Bullet list": "Puces",
"Header 1": "Titolo 1",
"Superscript": "Exposant",
"Clear formatting": "Effacer la mise en forme",
"Font Sizes": "Tailles de la police",
"Subscript": "Indice",
"Header 6": "Titolo 6",
"Redo": "R\u00e9tablir",
"Paragraph": "Paragrafo",
"Ok": "Ok",
"Bold": "Grassetto",
"Code": "Code",
"Italic": "Italico",
"Align center": "Centrer",
"Header 5": "Titolo 5",
"Heading 6": "En-t\u00eate 6",
"Heading 3": "En-t\u00eate 3",
"Decrease indent": "Diminuer le retrait",
"Header 4": "Titolo 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Le presse-papiers est maintenant en mode \"texte plein\". Les contenus seront coll\u00e9s sans retenir les formatages jusqu'\u00e0 ce que vous d\u00e9sactiviez cette option.",
"Underline": "Soulign\u00e9",
"Cancel": "Annulla",
"Justify": "Justifi\u00e9",
"Inline": "En ligne",
"Copy": "Copia",
"Align left": "Aligner \u00e0 gauche",
"Visual aids": "Aides visuelle",
"Lower Greek": "Grec minuscule",
"Square": "Carr\u00e9",
"Default": "Par d\u00e9faut",
"Lower Alpha": "Alpha minuscule",
"Circle": "Cercle",
"Disc": "Disque",
"Upper Alpha": "Alpha majuscule",
"Upper Roman": "Romain majuscule",
"Lower Roman": "Romain minuscule",
"Name": "Nome",
"Anchor": "Ancora",
"You have unsaved changes are you sure you want to navigate away?": "Vous avez des modifications non enregistr\u00e9es, \u00eates-vous s\u00fbr de quitter la page?",
"Restore last draft": "Restaurer le dernier brouillon",
"Special character": "Caract\u00e8res sp\u00e9ciaux",
"Source code": "Code source",
"Color": "Colore",
"Right to left": "Droite \u00e0 gauche",
"Left to right": "Gauche \u00e0 droite",
"Emoticons": "Emotic\u00f4nes",
"Robots": "Robots",
"Document properties": "Proprietà del documento",
"Title": "Titolo",
"Keywords": "Parole chiave",
"Encoding": "Codifica",
"Description": "Descrizione",
"Author": "Autore",
"Fullscreen": "Plein \u00e9cran",
"Horizontal line": "Linea orizzontale",
"Horizontal space": "Spazio Orizzontale",
"Insert\/edit image": "Inserisci\/modifica una immagine",
"General": "Generale",
"Advanced": "Avanzato",
"Source": "Fonte",
"Border": "Bordo",
"Constrain proportions": "Mantieni le proporzioni",
"Vertical space": "Spazio Verticale",
"Image description": "Descrizione della immagine",
"Style": "Stile",
"Dimensions": "Dimensioni",
"Insert image": "Inserisci una immagine",
"Insert date\/time": "Inserisci data\/ora",
"Remove link": "Rimuovi link",
"Url": "Url",
"Text to display": "Texte \u00e0 afficher",
"Anchors": "Ancore",
"Insert link": "Inserisci Link",
"New window": "Nuova finestra",
"None": "n\/a",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "L'URL que vous avez entr\u00e9e semble \u00eatre un lien externe. Voulez-vous ajouter le pr\u00e9fixe http:\/\/ n\u00e9cessaire?",
"Target": "Target",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "L'URL que vous avez entr\u00e9e semble \u00eatre une adresse e-mail. Voulez-vous ajouter le pr\u00e9fixe mailto: n\u00e9cessaire?",
"Insert\/edit link": "Ins\u00e9rer\/modifier un lien",
"Insert\/edit video": "Ins\u00e9rer\/modifier une vid\u00e9o",
"Poster": "Publier",
"Alternative source": "Source alternative",
"Paste your embed code below:": "Collez votre code d'int\u00e9gration ci-dessous :",
"Insert video": "Ins\u00e9rer une vid\u00e9o",
"Embed": "Int\u00e9grer",
"Nonbreaking space": "Espace ins\u00e9cable",
"Page break": "Saut de page",
"Paste as text": "Incolla come testo",
"Preview": "Pr\u00e9visualiser",
"Print": "Stampa",
"Save": "Salva",
"Could not find the specified string.": "Impossible de trouver la cha\u00eene sp\u00e9cifi\u00e9e.",
"Replace": "Sostituisci",
"Next": "Avanti",
"Whole words": "Parole intere",
"Find and replace": "Trova e Sostituisci",
"Replace with": "Sostituisci con",
"Find": "Trova",
"Replace all": "Sostituisci tutto",
"Match case": "Respecter la casse",
"Prev": "Pr\u00e9c ",
"Spellcheck": "V\u00e9rification orthographique",
"Finish": "Finito",
"Ignore all": "Ignora tutto",
"Ignore": "Ignora",
"Add to Dictionary": "Aggiungi al dizionario",
"Insert row before": "Inserisci riga prima",
"Rows": "Righe",
"Height": "Altezza",
"Paste row after": "Coller la ligne apr\u00e8s",
"Alignment": "Alignement",
"Border color": "Couleur de la bordure",
"Column group": "Groupe de colonnes",
"Row": "Riga",
"Insert column before": "Inserisci una colonna prima",
"Split cell": "Dividi la cella",
"Cell padding": "Espacement interne cellule",
"Cell spacing": "Espacement inter-cellulles",
"Row type": "Tipo di Linea",
"Insert table": "Ins\u00e9rer una tabella",
"Body": "Corpo",
"Caption": "Titolo",
"Footer": "Piè di pagina",
"Delete row": "Elimina la linea",
"Paste row before": "Incolla riga prima",
"Scope": "Portata",
"Delete table": "Elimina Tabella",
"H Align": "Alignement H",
"Top": "Top",
"Header cell": "Cellule d'en-t\u00eate",
"Column": "Colonne",
"Row group": "Groupe de lignes",
"Cell": "Cella",
"Middle": "Milieu",
"Cell type": "Tipo di cella",
"Copy row": "Copia Riga",
"Row properties": "Proprietà riga",
"Table properties": "Proprietà tabella",
"Bottom": "Bottom",
"V Align": "Alignement V",
"Header": "En-t\u00eate",
"Right": "Destra",
"Insert column after": "Ins\u00e9rer une colonne apr\u00e8s",
"Cols": "Colonnes",
"Insert row after": "Inserisci riga dopo",
"Width": "Larghezza",
"Cell properties": "Proprietà Cella",
"Left": "Sinistra",
"Cut row": "Taglia riga",
"Delete column": "Elimina la colonna",
"Center": "Centr\u00e9",
"Merge cells": "Fusionner les cellules",
"Insert template": "Inserisci un template",
"Templates": "Templates",
"Background color": "Couleur d'arri\u00e8re-plan",
"Custom...": "Personalizza...",
"Custom color": "Personalizza Colore",
"No color": "Nessun Colore",
"Text color": "Colore del testo",
"Show blocks": "Mostra blocchi",
"Show invisible characters": "Mostra caratteri invisibili",
"Words: {0}": "Parole : {0}",
"Insert": "Inserisci",
"File": "File",
"Edit": "Modifica",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text Area. Premi ALT-F9 per il menù. Premi ALT-F10 per la toolbar. Premi ALT-0 per la guida.",
"Tools": "Strumenti",
"View": "Vedi",
"Table": "Tabella",
"Format": "Formato"
});